apiVersion: apps/v1
kind: Deployment
metadata:
  name: componentprocessingms-deployment
  labels:
    app: ComponentProcessingMS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ComponentProcessingMS 
  template:
    metadata:
      labels:
        app: ComponentProcessingMS
    spec:
      containers:
      - name: ProjectContainerRes
        image: projectcontainerres.azurecr.io/projectcontainerres:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: componentprocessingmssvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ComponentProcessingMS